service: serverless-aws-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH